data:extend{
	{
		type = "string-setting",
		name = "grounded-tree-selection-box-size-basis",
		setting_type = "startup",
		order = "01",
		default_value = "original-selection-box",
		allowed_values = {
			"collision-box",
			"original-selection-box",
		},
	},
	{
		type = "string-setting",
		name = "grounded-tree-selection-box-position",
		setting_type = "startup",
		order = "02",
		default_value = "grounded-on-original-selection-box",
		allowed_values = {
			"centered-on-entity",
			"centered-on-collision-box",
			"grounded-on-collision-box",
			"grounded-on-original-selection-box",
		},
	},
	{
		type = "string-setting",
		name = "grounded-tree-selection-box-shape",
		setting_type = "startup",
		order = "03",
		default_value = "small-square",
		allowed_values = {
			"rectangle",
			"small-square",
			"large-square",
		},
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-horizontal-padding",
		setting_type = "startup",
		order = "04",
		default_value = -0.2,
		minimum_value = -1.0,
		maximum_value = 1.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-vertical-padding",
		setting_type = "startup",
		order = "05",
		default_value = -0.2,
		minimum_value = -1.0,
		maximum_value = 1.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-static-minimum-width",
		setting_type = "startup",
		order = "06",
		default_value = 0.8,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-static-minimum-height",
		setting_type = "startup",
		order = "07",
		default_value = 0.8,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-static-maximum-width",
		setting_type = "startup",
		order = "08",
		default_value = 0.0,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-static-maximum-height",
		setting_type = "startup",
		order = "09",
		default_value = 0.0,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-growable-minimum-width",
		setting_type = "startup",
		order = "10",
		default_value = 2.8,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-growable-minimum-height",
		setting_type = "startup",
		order = "11",
		default_value = 2.8,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-growable-maximum-width",
		setting_type = "startup",
		order = "12",
		default_value = 0.0,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
	{
		type = "double-setting",
		name = "grounded-tree-selection-box-growable-maximum-height",
		setting_type = "startup",
		order = "13",
		default_value = 0.0,
		minimum_value = 0.0,
		maximum_value = 4.0,
	},
}
